server:
  gzip:
      enabled: false
  applicationContextPath: /
  applicationConnectors:
    - type: http
      bindHost: 127.0.0.1 # only bind to loopback
      port: 10001
      

  adminContextPath: /admin
  adminConnectors:
    - type: http
      bindHost: 127.0.0.1 # only bind to loopback
      port: 4749

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ALL

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.apmasphere.billproto' to DEBUG.
    com.apmasphere.billproto: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
